### ISSUE TITLE
hi kwak ku won!

### ISSUE THREAD

**Issue by varvir** [girin-dev/python-Django-reviewer#1]
nice to meet you! README 에 링크 건 것들은 어떻게 한거야? 그리고 폴더안의 .md 파일은 어떻게 만들어?

**Comment by on29-dev** [comment]
ㅋㅋㅋ 자세한 것은 Markdown 작성법을 검색해보면 알겠지만 알려드림

1. 링크걸기
md문서에서 이렇게 작성하면 댐
`[링크 걸고자 하는 글](링크 url)`

2. 폴더 안에 md파일 만들기
그냥 폴더 안에 ___.md 파일 만들면 댐...

https://gist.github.com/ihoneymon/652be052a0727ad59601#26-%EB%A7%81%ED%81%AC 참고~
